language: node_js
node_js:
  # - '5'
  # - '6'
  - '7'
os:
- linux
# - osx

install:
  # - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` && ./install.sh) && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  # - echo $PATH
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i $DEB pandoc-1.19.2.1-1-amd64.deb
  - npm i -g docsmith
  - npm i -g

script:
  - git clone https://github.com/SAFETAG/SAFETAG
  - mkdir workspace && cd workspace && DEBUG=* safetag init --defaults && pwd
  - pwd
  - DEBUG=* safetag start --source $(pwd)/SAFETAG migrate
  - DEBUG=* safetag link activities ~/.content/build/@safetag/migrate/activities
  - DEBUG=* safetag start --debug toolkit

# addons:
#   apt:
#     packages:
#     - pandoc
deploy:
  local_dir: ~/.content/build/@safetag/toolkit
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

branches:
  only:
  - master
