language: node_js
node_js:
  # - '5'
  # - '6'
  - '7'
os:
- linux
# - osx

install:
  # - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` && ./install.sh) && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  # - echo $PATH
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i $DEB pandoc-1.19.2.1-1-amd64.deb
  - npm install -g npm
  - npm i -g docsmith@0.4.12
  - npm i -g

script:
  - mkdir workspace && cd workspace
  - DEBUG=* safetag init --defaults
  - git clone https://github.com/SAFETAG/SAFETAG
  # Fix missing symlinks manually
  - rm SAFETAG/es/reporting/content && rm SAFETAG/en/document_matter/content && rm SAFETAG/es/document_matter/content && rm SAFETAG/en/document_matter/en
  - DEBUG=* safetag start --source $(pwd)/SAFETAG migrate
  - DEBUG=* safetag start --debug --baseurl /safetag/@safetag/toolkit --package activities ~/.content/build/@safetag/migrate/activities toolkit

# addons:
#   apt:
#     packages:
#     - pandoc
deploy:
  local_dir: /home/travis/.content/build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

branches:
  only:
  - master
  except:
    - /^v[0-9]/
